/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'account-settings-tab': RouteRecordInfo<'account-settings-tab', '/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-technical-requests': RouteRecordInfo<'admin-technical-requests', '/admin/technical-requests', Record<never, never>, Record<never, never>>,
    'admin-users-franchisees': RouteRecordInfo<'admin-users-franchisees', '/admin/users/franchisees', Record<never, never>, Record<never, never>>,
    'admin-users-franchisors': RouteRecordInfo<'admin-users-franchisors', '/admin/users/franchisors', Record<never, never>, Record<never, never>>,
    'admin-users-sales': RouteRecordInfo<'admin-users-sales', '/admin/users/sales', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'franchisee-dashboard-finance': RouteRecordInfo<'franchisee-dashboard-finance', '/franchisee/dashboard/finance', Record<never, never>, Record<never, never>>,
    'franchisee-dashboard-operations': RouteRecordInfo<'franchisee-dashboard-operations', '/franchisee/dashboard/operations', Record<never, never>, Record<never, never>>,
    'franchisee-dashboard-sales': RouteRecordInfo<'franchisee-dashboard-sales', '/franchisee/dashboard/sales', Record<never, never>, Record<never, never>>,
    'franchisee-financial-overview': RouteRecordInfo<'franchisee-financial-overview', '/franchisee/financial-overview', Record<never, never>, Record<never, never>>,
    'franchisee-my-tasks': RouteRecordInfo<'franchisee-my-tasks', '/franchisee/my-tasks', Record<never, never>, Record<never, never>>,
    'franchisee-performance-management': RouteRecordInfo<'franchisee-performance-management', '/franchisee/performance-management', Record<never, never>, Record<never, never>>,
    'franchisee-royalty-management': RouteRecordInfo<'franchisee-royalty-management', '/franchisee/royalty-management', Record<never, never>, Record<never, never>>,
    'franchisee-technical-requests': RouteRecordInfo<'franchisee-technical-requests', '/franchisee/technical-requests', Record<never, never>, Record<never, never>>,
    'franchisee-unit-operation': RouteRecordInfo<'franchisee-unit-operation', '/franchisee/unit-operation', Record<never, never>, Record<never, never>>,
    'franchisor': RouteRecordInfo<'franchisor', '/franchisor', Record<never, never>, Record<never, never>>,
    'franchisor-add-lead': RouteRecordInfo<'franchisor-add-lead', '/franchisor/add-lead', Record<never, never>, Record<never, never>>,
    'franchisor-dashboard-finance': RouteRecordInfo<'franchisor-dashboard-finance', '/franchisor/dashboard/finance', Record<never, never>, Record<never, never>>,
    'franchisor-dashboard-leads': RouteRecordInfo<'franchisor-dashboard-leads', '/franchisor/dashboard/leads', Record<never, never>, Record<never, never>>,
    'franchisor-dashboard-operations': RouteRecordInfo<'franchisor-dashboard-operations', '/franchisor/dashboard/operations', Record<never, never>, Record<never, never>>,
    'franchisor-dashboard-timeline': RouteRecordInfo<'franchisor-dashboard-timeline', '/franchisor/dashboard/timeline', Record<never, never>, Record<never, never>>,
    'franchisor-financial-overview': RouteRecordInfo<'franchisor-financial-overview', '/franchisor/financial-overview', Record<never, never>, Record<never, never>>,
    'franchisor-franchise-registration': RouteRecordInfo<'franchisor-franchise-registration', '/franchisor/franchise-registration', Record<never, never>, Record<never, never>>,
    'franchisor-lead-management': RouteRecordInfo<'franchisor-lead-management', '/franchisor/lead-management', Record<never, never>, Record<never, never>>,
    'franchisor-leads-id': RouteRecordInfo<'franchisor-leads-id', '/franchisor/leads/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'franchisor-my-franchise': RouteRecordInfo<'franchisor-my-franchise', '/franchisor/my-franchise', Record<never, never>, Record<never, never>>,
    'franchisor-my-units': RouteRecordInfo<'franchisor-my-units', '/franchisor/my-units', Record<never, never>, Record<never, never>>,
    'franchisor-performance-management': RouteRecordInfo<'franchisor-performance-management', '/franchisor/performance-management', Record<never, never>, Record<never, never>>,
    'franchisor-royalty-management': RouteRecordInfo<'franchisor-royalty-management', '/franchisor/royalty-management', Record<never, never>, Record<never, never>>,
    'franchisor-sales-associates': RouteRecordInfo<'franchisor-sales-associates', '/franchisor/sales-associates', Record<never, never>, Record<never, never>>,
    'franchisor-tasks-management': RouteRecordInfo<'franchisor-tasks-management', '/franchisor/tasks-management', Record<never, never>, Record<never, never>>,
    'franchisor-technical-requests': RouteRecordInfo<'franchisor-technical-requests', '/franchisor/technical-requests', Record<never, never>, Record<never, never>>,
    'franchisor-units-id': RouteRecordInfo<'franchisor-units-id', '/franchisor/units/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'onboarding': RouteRecordInfo<'onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'sales-add-lead': RouteRecordInfo<'sales-add-lead', '/sales/add-lead', Record<never, never>, Record<never, never>>,
    'sales-lead-management': RouteRecordInfo<'sales-lead-management', '/sales/lead-management', Record<never, never>, Record<never, never>>,
    'sales-leads-id': RouteRecordInfo<'sales-leads-id', '/sales/leads/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'sales-my-tasks': RouteRecordInfo<'sales-my-tasks', '/sales/my-tasks', Record<never, never>, Record<never, never>>,
    'sales-technical-requests': RouteRecordInfo<'sales-technical-requests', '/sales/technical-requests', Record<never, never>, Record<never, never>>,
    'two-steps': RouteRecordInfo<'two-steps', '/two-steps', Record<never, never>, Record<never, never>>,
    'verify-email': RouteRecordInfo<'verify-email', '/verify-email', Record<never, never>, Record<never, never>>,
  }
}
